# Generated by Django 6.1.1 on 2026-09-05 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('sha256_root', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_id', models.CharField(max_length=100, unique=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('COMPLIANT', 'Compliant'), ('DISQUALIFIED', 'Disqualified'), ('CLARIFICATION_DISPATCHED', 'Clarification Dispatched')], default='UNDER_REVIEW', max_length=50)),
                ('precheck_score', models.FloatField(default=66.7)),
            ],
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_compliance', models.FloatField(default=83.3)),
                ('summary', models.TextField()),
                ('recommended_action', models.CharField(default='REQUEST_CLARIFICATION', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='api.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bidder_id', models.CharField(max_length=100, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=20)),
                ('gstin', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.bidder'),
        ),
        migrations.CreateModel(
            name='CrossCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('source1', models.CharField(max_length=100)),
                ('source2', models.CharField(max_length=100)),
                ('value1', models.TextField()),
                ('value2', models.TextField()),
                ('match_score', models.FloatField(default=100.0)),
                ('result', models.CharField(default='MATCH', max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_checks', to='api.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='application/pdf', max_length=50)),
                ('storage_path', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('GST_CERTIFICATE', 'GST Certificate'), ('PAN', 'PAN Card'), ('UDYAM', 'Udyam MSME Certificate'), ('AUDITED_FINANCIAL_STATEMENT', 'Audited Financial Statement'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('OEM_AUTHORIZATION', 'OEM Authorization Form 8-B'), ('WORK_ORDER', 'Work Order'), ('OTHER', 'Other Document')], default='OTHER', max_length=100)),
                ('sha256_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.CharField(default='1.2 MB', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('OCR_COMPLETED', 'OCR Completed'), ('EXTRACTION_COMPLETED', 'Extraction Completed'), ('FAILED', 'Failed')], default='EXTRACTION_COMPLETED', max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.bid')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('confidence', models.FloatField(default=0.98)),
                ('page_number', models.IntegerField(default=1)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('dsc_pin_verified', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.bid')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('affected_requirement', models.CharField(max_length=100)),
                ('risk_points', models.IntegerField(default=15)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='api.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('department', models.CharField(default='MoPNG / GAIL', max_length=255)),
                ('category', models.CharField(default='Works / Critical Infrastructure', max_length=255)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField()),
                ('tender_type', models.CharField(default='Turnkey / EPC', max_length=100)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=50000000.0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNDER_REVIEW', 'Under Review'), ('EVALUATED', 'Evaluated'), ('CLOSED', 'Closed')], default='PUBLISHED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.tender'),
        ),
        migrations.CreateModel(
            name='TenderRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(max_length=50)),
                ('clause_number', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mandatory', models.BooleanField(default=True)),
                ('threshold', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_evidence', models.CharField(max_length=255)),
                ('rule', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule', models.TextField()),
                ('input_value', models.TextField()),
                ('result', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('MISSING', 'Missing'), ('EXPIRED', 'Expired'), ('INCONSISTENT', 'Inconsistent'), ('REQUIRES_REVIEW', 'Requires Review')], default='COMPLIANT', max_length=50)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='api.bid')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('COMPLIANCE_REVIEWER', 'Compliance Reviewer'), ('BIDDER', 'Bidder'), ('AUDITOR', 'Auditor')], default='PROCUREMENT_OFFICER', max_length=50)),
                ('department', models.CharField(default='Ministry of Petroleum & Natural Gas', max_length=255)),
                ('organization', models.CharField(default='GAIL (India) Limited', max_length=255)),
                ('dsc_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('submitted_value', models.TextField()),
                ('verified_value', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('NOT_FOUND', 'Not Found'), ('EXPIRED', 'Expired'), ('MISMATCH', 'Mismatch'), ('NEEDS_REVIEW', 'Needs Review')], default='VERIFIED', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='api.bid')),
            ],
        ),
    ]
